AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: DynamoDB tables that are required for handling the Zoom Symbl Integration

Resources:

  ZoomRecordingsDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: zoom_recordings
      AttributeDefinitions:
        - AttributeName: meeting_uuid
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: "meeting_uuid"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

  ZoomRecordingsInsightsDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: zoom_recordings_insights
      AttributeDefinitions:
        - AttributeName: conversation_id
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: "conversation_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

  ZoomRecordingsJobsDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: zoom_recordings_jobs
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: "job_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

  ZoomRecordingsJobsCountDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: zoom_recordings_jobs_count
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0