AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Zoom Recording Completed
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          
  ZoomRecordingComplete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: Zoom Recording Completed
      MemorySize: 128
      Timeout: 900
      Policies:
        Statement:
          Sid: AllowCopyZoomRecordingToS3
          Effect: Allow
          Action: lambda:InvokeFunction
          Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ZoomRecordingComplete
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      
