AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Create an Zoom Symbl Integration Layers"

Resources: 
    RequestsLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: requests_layer
        Description: Requests Layer
        ContentUri: ./layer/requests.zip
        CompatibleRuntimes:
          - python3.6
          - python3.7
          - python3.8
          - python3.9
        LicenseInfo: 'Available under the MIT-0 license.'
        RetentionPolicy: Retain

    FFMPEGLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: ffmpeg_layer
        Description: FFMPEG layer
        ContentUri: ./layer/ffmpeglib.zip
        CompatibleRuntimes:
          - python3.6
          - python3.7
          - python3.8
          - python3.9
        LicenseInfo: 'Available under the MIT-0 license.'
        RetentionPolicy: Retain   